import { Metadata } from "next";

import SearchBox from "@/components/MyComponents/SearchBox";
import AddItemModal from "@/components/MyComponents/AddItemModal/AddItemModal";

export const metadata: Metadata = {
  title: "IMS: Inventory",
  description: "Generated by create next app",
};

export default function InventoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex min-h-screen flex-col gap-12 py-12 pl-[123px] pr-12 text-text">
      <SearchBox />
      <AddItemModal />
      {children}
    </main>
  );
}
