import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar/Navbar";
import NavLink from "@/components/Navbar/NavLink";
import CustomBsHouseFill from "@/components/CustomBSIcons/CustomBsHouseFill";
import CustomBsArchiveFill from "@/components/CustomBSIcons/CustomBsArchiveFill";
import CustomBsInfoCircleFill from "@/components/CustomBSIcons/CustomBsHouseFill copy";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} bg-background`}>
        <Navbar>
          <NavLink label="Home" href="/">
            <CustomBsHouseFill />
          </NavLink>
          <NavLink label="Inventory" href="/inventory">
            <CustomBsArchiveFill />
          </NavLink>
          <NavLink label="About" href="/about">
            <CustomBsInfoCircleFill />
          </NavLink>
        </Navbar>

        {children}
      </body>
    </html>
  );
}
